### ISSUE TITLE
Expected Cases 

### ISSUE THREAD

**Issue by nkamkolkar** [ravi-prakash1907/COVID-19-India#1]
@ravi-prakash1907 - thank you so much for your contributions. Can you share if the source of this data is from an official health ministry or some other organization. I want to know since I use John Hopkins world wide data for my analytics and noticed you were merging these in. Appreciate any context on the data and how it's being gathered - example, are you generating the expected case column via predictions or is this being provisioned to you via some external health organization.

**Comment by ravi-prakash1907** [comment]
Thanks @nkamkolkar for your arrival. I'm collecting the actual data provided by the official website of **Ministry of Health and Family Welfare - India**
There is a single table that they update on the daily basis.. yet i manage to collect this every day, in order to create a _time series_ dataset.

I've externally appended the Latitude & Longitude positions of respective States after extracting, as government does not provide us the position with this data.

To explore further, you can visit the official website of Indian Ministry of Health and Family Welfare **(MoHFW)** at https://www.mohfw.gov.in/

Just click on the *State Data* & you'll be greeted with the State-wise data till that day.

<hr />

The directories, **except** https://github.com/ravi-prakash1907/COVID-19-India/tree/master/time_series_data/ready hold the files that I use for my analysis.

**Comment by nkamkolkar** [comment]
Thank you Ravi for the information. Appreciate your collation. For my
analysis, I need to be sure about how data is being gathered and
interpreted. Appreciate your explanation on this.

Are you factoring in as recovered the columns?   *Cured/Discharged/*
*Migrated*

I would probably not want to club those as recovered - as it's not clear to
me whether the migrated cases may actually are tested. They could be part
of the asymptomatic group, which is why I don't think we should tabulate
those as recovered. John Hopkins had removed the recovered count in the US
as this was not a reliable number.

Again, appreciate your community contributions. Please let me know if I can
help in anyways. I plan to use this data for some analytics in the future.

**Comment by ravi-prakash1907** [comment]
You got it right! Recovered column clubs them altogether, as we do not have this data separately.

Although based on the data received earlier, I also have the Confirmed Cases splitted into two columns i.e. **Foreign** & **Indian** nationalists. Perhaps, it might prove to be helpful for you too.

(You can have a look into that at https://github.com/ravi-prakash1907/COVID-19-India/blob/master/india-today/covid_19_india.csv)
I don't find it more reliable because this splitting is available only till March 28<sup>th</sup>

I really appreciate that you aim to do your further analysis on this data. Probably we could collaborate in future ;)
